//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OITReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientMaster
    {
        public int clientId { get; set; }
        public int userId { get; set; }
        public int domainId { get; set; }
        public string status { get; set; }
        public string emailId { get; set; }
        public string companyName { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonDesignation { get; set; }
        public decimal contactPersonContactNo1 { get; set; }
        public Nullable<decimal> contactPersonContactNo2 { get; set; }
        public Nullable<decimal> companyCellPhone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int counytryId { get; set; }
        public Nullable<bool> isResponded { get; set; }
        public Nullable<bool> isUnsubscribe { get; set; }
    
        public virtual domainMaster domainMaster { get; set; }
        public virtual userMaster userMaster { get; set; }
        public virtual emailSendingHistory emailSendingHistory { get; set; }
    }
}
