//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OITReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailSendingHistory
    {
        public int id { get; set; }
        public int clientId { get; set; }
        public System.DateTime emailDate { get; set; }
        public string emailType { get; set; }
        public Nullable<bool> isResponded { get; set; }
        public Nullable<bool> isUnsubscribe { get; set; }
    
        public virtual clientMaster clientMaster { get; set; }
    }
}
