//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OITReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public int stateId { get; set; }
        public string stateName { get; set; }
        public int countryId { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
