//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OITReporting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("userMaster")]
    public partial class userMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userMaster()
        {
            this.clientMasters = new HashSet<clientMaster>();
        }
        
        public int userId { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter first name", AllowEmptyStrings = false)]
        public string firstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter last name", AllowEmptyStrings = false)]
        public string lastName { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please select your date of birth", AllowEmptyStrings = false)]
        public System.DateTime dob { get; set; }

        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Please select your gender", AllowEmptyStrings = false)]
        public string gender { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "Please enter residental address", AllowEmptyStrings = false)]
        public string address { get; set; }

        [Display(Name = "Country")]
        [Required(ErrorMessage = "Please select country", AllowEmptyStrings = false)]
        public string city { get; set; }

        [Display(Name = "State")]
        [Required(ErrorMessage = "Please select state", AllowEmptyStrings = false)]
        public string state { get; set; }

        [Display(Name = "City")]
        [Required(ErrorMessage = "Please select city", AllowEmptyStrings = false)]
        public int countryId { get; set; }

        [Required(ErrorMessage = "Please enter contact number", AllowEmptyStrings = false)]
        [Display(Name = "Contact No.")]
        public decimal contactNo { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please enter email address", AllowEmptyStrings = false)]
        [EmailAddress(ErrorMessage = "Entered email address is invalid")]
        public string emailID { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please enter password", AllowEmptyStrings = false)]
        public string password { get; set; }

        public Nullable<bool> rememberMe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientMaster> clientMasters { get; set; }
    }
}
